name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: aws
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 43.199.105.61
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /data/www/www.readtheone
          git pull
          yarn build
          sudo supervisorctl restart www.readtheone:
